// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK5G2q_6RmU-COdBOFmwga-SWcPefcg1E',
    appId: '1:239037972513:web:aec9d57c401045eaf6e360',
    messagingSenderId: '239037972513',
    projectId: 'park-on-c33b4',
    authDomain: 'park-on-c33b4.firebaseapp.com',
    storageBucket: 'park-on-c33b4.firebasestorage.app',
    measurementId: 'G-91EYEENV2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFlkI4j0LQbo2LwMEHXdEBEDx719QyK4k',
    appId: '1:239037972513:android:282bffb97af4df48f6e360',
    messagingSenderId: '239037972513',
    projectId: 'park-on-c33b4',
    storageBucket: 'park-on-c33b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy7JxdZblXvJ69FyNkJrayBcbaHjVL4kc',
    appId: '1:239037972513:ios:9ab3a851c44bd040f6e360',
    messagingSenderId: '239037972513',
    projectId: 'park-on-c33b4',
    storageBucket: 'park-on-c33b4.firebasestorage.app',
    iosBundleId: 'com.example.parking2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy7JxdZblXvJ69FyNkJrayBcbaHjVL4kc',
    appId: '1:239037972513:ios:9ab3a851c44bd040f6e360',
    messagingSenderId: '239037972513',
    projectId: 'park-on-c33b4',
    storageBucket: 'park-on-c33b4.firebasestorage.app',
    iosBundleId: 'com.example.parking2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK5G2q_6RmU-COdBOFmwga-SWcPefcg1E',
    appId: '1:239037972513:web:1ffee640d09c9d28f6e360',
    messagingSenderId: '239037972513',
    projectId: 'park-on-c33b4',
    authDomain: 'park-on-c33b4.firebaseapp.com',
    storageBucket: 'park-on-c33b4.firebasestorage.app',
    measurementId: 'G-6VH5VR8ZHP',
  );
}
